import { COUNTRY_TIMEZONE } from "./constants";
import type {
  CityVibePost,
  LookingFor,
  Reel,
  ReelFlag,
  SoftLaunchStory,
  UserProfile,
} from "./types";

const looking: LookingFor[] = [
  "soft-launch",
  "situationship",
  "serious",
  "casual",
  "friends-to-lovers",
  "talking-stage",
  "open",
  "long-distance",
];

const flags: ReelFlag[] = ["green", "red", "neutral", "green", "green", "red", "neutral", "green", "red", "green"];

export const MOCK_PROFILES: UserProfile[] = [
  {
    id: "u1",
    email: "maya@example.com",
    name: "Maya",
    age: 24,
    birthday: "2001-03-14",
    gender: "woman",
    bio: "Soft launching myself until further notice. Dog mom. Cold brew dependent.",
    city: "Brooklyn",
    country: "United States",
    countryCode: "US",
    photos: [
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["soft-launch", "serious"],
    interests: ["Coffee runs", "Dogs", "Photography", "Concerts"],
    prompts: [
      { prompt: "Green flag I look for…", answer: "Texts back and shows up on time" },
      { prompt: "My ideal first date…", answer: "Sunset walk + dumplings" },
    ],
    languages: ["English", "Spanish"],
    verified: true,
    distanceKm: 3,
    lastActive: "Just now",
    timezone: COUNTRY_TIMEZONE.US,
  },
  {
    id: "u2",
    email: "jordan@example.com",
    name: "Jordan",
    age: 27,
    birthday: "1998-07-22",
    gender: "man",
    bio: "Building something weird. Looking for someone who gets the bit.",
    city: "Austin",
    country: "United States",
    countryCode: "US",
    photos: [
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["talking-stage", "casual", "open"],
    interests: ["Startup life", "Hiking", "Gaming", "Memes"],
    prompts: [
      { prompt: "My toxic trait is…", answer: "Turning everything into a bit" },
      { prompt: "I'll fall for you if…", answer: "You can roast me without mercy" },
    ],
    languages: ["English"],
    verified: true,
    distanceKm: 12,
    lastActive: "2h ago",
    timezone: "America/Chicago",
  },
  {
    id: "u3",
    email: "aisha@example.com",
    name: "Aisha",
    age: 25,
    birthday: "2000-11-02",
    gender: "woman",
    bio: "Main character energy. Situationships need not apply.",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    photos: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["serious", "marriage-minded"],
    interests: ["Art galleries", "Poetry", "Travel", "Skincare"],
    prompts: [
      { prompt: "I'm looking for someone who…", answer: "Has emotional vocabulary" },
      { prompt: "Soft launching me looks like…", answer: "A blurry cafe story" },
    ],
    languages: ["English", "French", "Yoruba"],
    verified: true,
    distanceKm: 8,
    lastActive: "Online",
    timezone: COUNTRY_TIMEZONE.GB,
  },
  {
    id: "u4",
    email: "leo@example.com",
    name: "Leo",
    age: 26,
    birthday: "1999-01-18",
    gender: "man",
    bio: "Surfer by morning, playlist curator by night. Let's not define it yet.",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    photos: [
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["situationship", "casual", "friends-to-lovers"],
    interests: ["Surfing", "Festivals", "Street food", "Yoga"],
    prompts: [
      { prompt: "The way to my heart is…", answer: "Sunrise swims and bad jokes" },
      { prompt: "A life goal of mine…", answer: "Live somewhere with ocean access" },
    ],
    languages: ["English"],
    verified: false,
    distanceKm: 5,
    lastActive: "1d ago",
    timezone: COUNTRY_TIMEZONE.AU,
  },
  {
    id: "u5",
    email: "priya@example.com",
    name: "Priya",
    age: 23,
    birthday: "2002-05-09",
    gender: "woman",
    bio: "K-drama emotional damage survivor seeking green flags only.",
    city: "Bangalore",
    country: "India",
    countryCode: "IN",
    photos: [
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["friends-to-lovers", "talking-stage", "soft-launch"],
    interests: ["K-drama", "Coffee runs", "Book clubs", "Thrifting"],
    prompts: [
      { prompt: "My most controversial opinion…", answer: "Pineapple on pizza is elite" },
      { prompt: "Green flag I look for…", answer: "Remembers the little things" },
    ],
    languages: ["English", "Hindi", "Kannada"],
    verified: true,
    distanceKm: 4,
    lastActive: "Just now",
    timezone: COUNTRY_TIMEZONE.IN,
  },
  {
    id: "u6",
    email: "sam@example.com",
    name: "Sam",
    age: 28,
    birthday: "1997-09-30",
    gender: "nonbinary",
    bio: "Artist. Night owl. Looking for long-distance that actually works.",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    photos: [
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["long-distance", "open", "serious"],
    interests: ["Photography", "Concerts", "Astrology", "Sustainability"],
    prompts: [
      { prompt: "My ideal first date…", answer: "Museum then late-night noodles" },
      { prompt: "I'm looking for someone who…", answer: "Can handle silence comfortably" },
    ],
    languages: ["English", "German"],
    verified: true,
    distanceKm: 15,
    lastActive: "4h ago",
    timezone: COUNTRY_TIMEZONE.DE,
  },
  {
    id: "u7",
    email: "kenji@example.com",
    name: "Kenji",
    age: 29,
    birthday: "1996-12-12",
    gender: "man",
    bio: "Tokyo nights and good ramen. Here for intentional dating.",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    photos: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["serious", "soft-launch"],
    interests: ["Anime", "Street food", "Photography", "Gym rat"],
    prompts: [
      { prompt: "I'll fall for you if…", answer: "You can keep up with my playlist" },
      { prompt: "Two truths and a lie…", answer: "I climb. I cook. I hate cats." },
    ],
    languages: ["Japanese", "English"],
    verified: true,
    distanceKm: 7,
    lastActive: "Online",
    timezone: COUNTRY_TIMEZONE.JP,
  },
  {
    id: "u8",
    email: "lucia@example.com",
    name: "Lucía",
    age: 24,
    birthday: "2001-08-21",
    gender: "woman",
    bio: "Dancer. Chaos coordinator. Soft launch certified.",
    city: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    photos: [
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["casual", "situationship", "new-friends"],
    interests: ["Dancing", "Festivals", "Coffee runs", "Travel"],
    prompts: [
      { prompt: "The way to my heart is…", answer: "Spontaneous dance floor energy" },
      { prompt: "Soft launching me looks like…", answer: "A hand in a car selfie" },
    ],
    languages: ["Spanish", "English"],
    verified: false,
    distanceKm: 9,
    lastActive: "3h ago",
    timezone: COUNTRY_TIMEZONE.MX,
  },
  {
    id: "u9",
    email: "noah@example.com",
    name: "Noah",
    age: 26,
    birthday: "1999-04-04",
    gender: "man",
    bio: "Podcast-obsessed. Looking for friends-to-lovers arc.",
    city: "Toronto",
    country: "Canada",
    countryCode: "CA",
    photos: [
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["friends-to-lovers", "talking-stage"],
    interests: ["Podcasts", "Hiking", "Board games", "Coffee runs"],
    prompts: [
      { prompt: "My toxic trait is…", answer: "Sending 12-minute voice notes" },
      { prompt: "A life goal of mine…", answer: "Host a dinner party that doesn't flop" },
    ],
    languages: ["English", "French"],
    verified: true,
    distanceKm: 6,
    lastActive: "Just now",
    timezone: COUNTRY_TIMEZONE.CA,
  },
  {
    id: "u10",
    email: "zara@example.com",
    name: "Zara",
    age: 22,
    birthday: "2003-02-28",
    gender: "woman",
    bio: "Fashion student. Green flag hunter. Globally down.",
    city: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    photos: [
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&h=1000&fit=crop",
    ],
    lookingFor: ["open", "long-distance", "serious"],
    interests: ["Thrifting", "Skincare", "Travel", "Art galleries"],
    prompts: [
      { prompt: "Green flag I look for…", answer: "Curious about the world" },
      { prompt: "My ideal first date…", answer: "Gallery hop then dessert crawl" },
    ],
    languages: ["English", "Arabic", "Urdu"],
    verified: true,
    distanceKm: 11,
    lastActive: "5h ago",
    timezone: COUNTRY_TIMEZONE.AE,
  },
];

const captions = [
  "POV: first date energy ✨",
  "soft launch practice run",
  "tell me this isn't main character coded",
  "day in my life if we matched",
  "green flags only challenge",
  "red flag? I call it personality",
  "timezone date outfit check",
];

/** Fixed anchor so mock timestamps match between SSR and the WebView client. */
const MOCK_NOW = Date.parse("2026-07-16T12:00:00.000Z");

export const MOCK_REELS: Reel[] = MOCK_PROFILES.flatMap((p, i) => [
  {
    id: `r-${p.id}-1`,
    userId: p.id,
    videoUrl: "",
    posterUrl: p.photos[0],
    caption: captions[i % captions.length],
    likes: 120 + i * 37,
    createdAt: new Date(MOCK_NOW - i * 3600000).toISOString(),
    flag: flags[i % flags.length],
    isMainCharacter: i % 3 === 0,
  },
  {
    id: `r-${p.id}-2`,
    userId: p.id,
    videoUrl: "",
    posterUrl: p.photos[1] ?? p.photos[0],
    caption: looking[i % looking.length].replace(/-/g, " ") + " era",
    likes: 80 + i * 21,
    createdAt: new Date(MOCK_NOW - i * 7200000).toISOString(),
    flag: flags[(i + 2) % flags.length],
    isAuraBoost: i === 1,
    boostExpiresAt:
      i === 1 ? new Date(MOCK_NOW + 1000 * 60 * 45).toISOString() : undefined,
  },
]);

export const MOCK_CITY_VIBES: CityVibePost[] = [
  {
    id: "cv1",
    city: "Brooklyn",
    countryCode: "US",
    prompt: "Best low-key 2nd date spot here?",
    answer: "Domino Park at golden hour — zero pressure, max vibe.",
    createdAt: new Date(MOCK_NOW - 3600000).toISOString(),
    anonymousHandle: "coldbrew.kid",
    authorId: "u1",
    tags: ["Coffee runs", "Dogs"],
  },
  {
    id: "cv2",
    city: "Bangalore",
    countryCode: "IN",
    prompt: "Where do soft launches happen in this city?",
    answer: "Cubbon Park walks + filter so heavy nobody knows it's a date.",
    createdAt: new Date(MOCK_NOW - 7200000).toISOString(),
    anonymousHandle: "filter.soft",
    authorId: "u5",
    tags: ["Coffee runs", "Book clubs"],
  },
  {
    id: "cv3",
    city: "London",
    countryCode: "GB",
    prompt: "Greenest flag neighborhood energy?",
    answer: "Hackney people who show up on time. Rare. Sacred.",
    createdAt: new Date(MOCK_NOW - 10800000).toISOString(),
    anonymousHandle: "gallery.hours",
    authorId: "u3",
    tags: ["Art galleries", "Poetry"],
  },
  {
    id: "cv4",
    city: "Berlin",
    countryCode: "DE",
    prompt: "Late-night food that impresses?",
    answer: "Döner after a gallery. If they get it, marry them.",
    createdAt: new Date(MOCK_NOW - 14400000).toISOString(),
    anonymousHandle: "night.owl",
    authorId: "u6",
    tags: ["Photography", "Concerts"],
  },
  {
    id: "cv5",
    city: "Tokyo",
    countryCode: "JP",
    prompt: "Most main-character walk route?",
    answer: "Shimokitazawa at 10pm with headphones. Instant soft life.",
    createdAt: new Date(MOCK_NOW - 18000000).toISOString(),
    anonymousHandle: "ramen.run",
    authorId: "u7",
    tags: ["Street food", "Anime"],
  },
  {
    id: "cv6",
    city: "Dubai",
    countryCode: "AE",
    prompt: "Best low-key 2nd date spot here?",
    answer: "Alserkal gallery hop then karak. Quiet flex.",
    createdAt: new Date(MOCK_NOW - 21600000).toISOString(),
    anonymousHandle: "desert.drip",
    authorId: "u10",
    tags: ["Art galleries", "Travel"],
  },
];

export const MOCK_SOFT_LAUNCH_FEED: SoftLaunchStory[] = [
  {
    id: "sl1",
    matchId: "demo",
    userId: "u1",
    partnerId: "u9",
    partnerName: "N.",
    caption: "hand + latte. that's the tweet.",
    posterUrl:
      "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=800&h=1000&fit=crop",
    createdAt: new Date(MOCK_NOW - 5400000).toISOString(),
    isPublic: true,
  },
  {
    id: "sl2",
    matchId: "demo2",
    userId: "u5",
    partnerId: "u2",
    partnerName: "J.",
    caption: "blurry on purpose",
    posterUrl:
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=1000&fit=crop",
    createdAt: new Date(MOCK_NOW - 9000000).toISOString(),
    isPublic: true,
  },
  {
    id: "sl3",
    matchId: "demo3",
    userId: "u8",
    partnerId: "u4",
    partnerName: "L.",
    caption: "not naming names (yet)",
    posterUrl:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&h=1000&fit=crop",
    createdAt: new Date(MOCK_NOW - 12600000).toISOString(),
    isPublic: true,
  },
];

export function getProfileById(id: string) {
  return MOCK_PROFILES.find((p) => p.id === id);
}
